# This is a basic workflow to help you get started with Actions

name: "datapackage_tabular-data (build)"

concurrency: 
  group: "datapackage_tabular-data_build"
  cancel-in-progress: true
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the 4.4.x branch
  push:
    branches: [ datapackage_tabular-data ]
    paths: 
      - "VERSION"
      - "geonode_mapstore_client/client/**"
      - "!geonode_mapstore_client/client/version.txt"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_commit:
    env:
      working-directory: ./geonode_mapstore_client/client
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      ###########
      # SET UP 
      #########
      - name: "Setting up npm"
        uses: actions/setup-node@v4
        with:
            node-version: 20

      ############
      # CACHING
      ##########
      - name: "Cache node modules"
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      ###############
      # NPM BUILD
      #############
      - name: "Run npm install"
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: "Run npm compile"
        run: npm run compile
        working-directory: ${{env.working-directory}}

      ###############
      # COMMIT
      #############
      - name: "Stage files"
        run: git add --all
        
      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[datapackage_tabular-data] new JS dist build"
          body: "CI build on branch `datapackage_tabular-data`"
          delete-branch: true
